Traceback (most recent call last):
  File "/Users/User/anaconda3/envs/jupyterbooks/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/User/anaconda3/envs/jupyterbooks/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/User/anaconda3/envs/jupyterbooks/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/User/anaconda3/envs/jupyterbooks/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/User/anaconda3/envs/jupyterbooks/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/User/anaconda3/envs/jupyterbooks/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/User/anaconda3/envs/jupyterbooks/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#data_1 = pd.DataFrame({'resistencia': [10.,20.,50.,70.,100.,150.],
                       'voltaje': [1371.,1420.,1452.,1461.,1465.,1469.]})
#
#data_2 = pd.DataFrame({'resistencia': [10.,20.,50.,100.,150.],
#                       'voltaje': [241.,416.,727.,973.,1097.]})
#
#data_3 = pd.DataFrame({'resistencia': [20.,50.,70.,100.,150.],
#                       'voltaje': [719.,1036.,1132.,1217.,1291]})
------------------


[0;36m  Cell [0;32mIn[3], line 2[0;36m[0m
[0;31m    'voltaje': [1371.,1420.,1452.,1461.,1465.,1469.]})[0m
[0m    ^[0m
[0;31mIndentationError[0m[0;31m:[0m unexpected indent


